[project]
name = "agentic-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "langchain>=1.2.8",
    "langchain-nvidia-ai-endpoints>=1.0.3",
    "streamlit>=1.54.0",
]
